name: "🚀 Pages"

on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: "GitHub Pages"
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Get source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        env:
          GH_TOKEN_MATERIAL_INSIDERS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade -r requirements/documentation.txt

      - name: Cache build dependencies (external assets downloaded)
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Build static website
        run: |
          mkdocs build --clean --config-file mkdocs.yml --verbose --strict
          ls

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: "site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
