name: "✅ Linter"

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - '**.py'

env:
  PYTHON_VERSION: 3.12


jobs:
  ruff:
    name: Python 🐍

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: "requirements/development.txt"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/development.txt

      - name: Lint with flake8
        run: |
          ruff check
